name: jio_reactor
description: "A Flutter package for android, iOS and web which provides reactive widget."
version: 0.0.1
homepage: https://github.com/JioCoders/jio_reactor.git
repository: https://github.com/JioCoders/jio_reactor.git
issue_tracker: https://github.com/JioCoders/jio_reactor/issues
topics:
  - reactive-widget
  - controller
  - reactor
  - rxdart

environment:
  sdk: ^3.8.1
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.28.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  logger: ^2.6.0
  
# The following section is specific to Flutter packages.
flutter:

  # To add assets to your package, add an assets section, like this:
  # assets:
  #   - images/a_dot_burr.jpeg
